version: "3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SEM7
    environment:
      SA_PASSWORD: "12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
